config/routes.rb
Xantar::Application.routes.draw do

  root 'easy_pages#index'
  get 'laptops' => 'easy_pages#laptops', as: :laptops
  get 'monitors' => 'easy_pages#monitors', as: :monitors

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/easy_pages_controller.rb
class EasyPagesController < ApplicationController

  def index
    SEMANTICS.products_field("cat_id", 13658)
    SEMANTICS.products_field("name", search_parameters[:search])
    @products_index = SEMANTICS.get_products()
  end

  def laptops
    SEMANTICS.products_field("cat_id", 12855)
    SEMANTICS.products_field("name", search_parameters[:search])
    @products_index = SEMANTICS.get_products()
  end

  def monitors
    SEMANTICS.products_field("cat_id", 12460)
    SEMANTICS.products_field("name", search_parameters[:search])
    @products_index = SEMANTICS.get_products()
  end

  private

  def search_parameters
    params.permit(:search).permit(:search)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/easy_pages_helper.rb
module EasyPagesHelper
end

app/views/easy_pages/index.html.erb
<h1>Searching through the electronics category</h1>
<%= form_tag root_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% @products_index['results'].each do |product| %>
  <li><%= product['name'] %></li>
<% end %>

app/views/easy_pages/laptops.html.erb
<h1>Searching through the Laptops category</h1> <h2><%= link_to "Electronics", root_path %></h2> <h2><%= link_to "Monitors", monitors_path %></h2>
<%= form_tag laptops_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% @products_index['results'].each do |product| %>
  <li><%= product['name'] %></li>
<% end %>

app/views/easy_pages/monitors.html.erb
<h1>Searching through the Monitors category</h1> <h2><%= link_to "Electronics", root_path %></h2> <h2><%= link_to "Laptops", laptops_path %></h2>
<%= form_tag monitors_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% @products_index['results'].each do |product| %>
  <li><%= product['name'] %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xantar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>